# -*- coding: utf-8 -*-
"""bcg genai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pf4_w6wIcLkF8oSLOSVWFbb48A4oGrpr
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/fiscal.csv")

df

# Calculate Revenue Growth (%) and Net Income Growth (%)
df['Revenue Growth (%)'] = df.groupby(['Company '])['Total Revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby(['Company '])['Net Income'].pct_change() * 100

# Create a new DataFrame to display growth metrics in tabular format
growth_table = df[['Company ', 'Fiscal Year', 'Revenue Growth (%)', 'Net Income Growth (%)']].copy()
growth_table.fillna(0, inplace=True)  # Replace NaN with 0 for better readability
print("Growth Metrics Table:")
print(growth_table.to_string(index=False))

# prompt: create a simple chat bot

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/fiscal.csv")

df

# Calculate Revenue Growth (%) and Net Income Growth (%)
df['Revenue Growth (%)'] = df.groupby(['Company '])['Total Revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby(['Company '])['Net Income'].pct_change() * 100

# Create a new DataFrame to display growth metrics in tabular format
growth_table = df[['Company ', 'Fiscal Year', 'Revenue Growth (%)', 'Net Income Growth (%)']].copy()
growth_table.fillna(0, inplace=True)  # Replace NaN with 0 for better readability

# Simple chatbot functionality
def chatbot():
    print("Welcome to the Financial Growth Chatbot!")
    while True:
        user_input = input("Ask me about revenue or net income growth (or type 'exit'): ").lower()
        if user_input == 'exit':
            break
        elif "revenue growth" in user_input:
            company = input("For which company? ")
            year = input("For which fiscal year? ")
            try:
              growth = growth_table[(growth_table['Company '] == company) & (growth_table['Fiscal Year'] == int(year))]['Revenue Growth (%)'].iloc[0]
              print(f"The revenue growth for {company} in {year} was {growth:.2f}%.")
            except (IndexError, ValueError):
                print("Data not found for the specified company and year.")

        elif "net income growth" in user_input:
            company = input("For which company? ")
            year = input("For which fiscal year? ")
            try:
              growth = growth_table[(growth_table['Company '] == company) & (growth_table['Fiscal Year'] == int(year))]['Net Income Growth (%)'].iloc[0]
              print(f"The net income growth for {company} in {year} was {growth:.2f}%.")
            except (IndexError, ValueError):
                print("Data not found for the specified company and year.")
        else:
            print("I'm sorry, I don't understand your question.")

chatbot()